services:
  deivao-recon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deivao-recon
    volumes:
      # Monta a pasta de resultados no host
      - ~/Documents/Bugbounty:/root/Documents/Bugbounty
    working_dir: /app
    stdin_open: true
    tty: true

